alias ga='git add -A'

alias gc='git commit -a'
alias gn='git commit -an'
alias gam='git commit --amend'

alias gco='git checkout'
alias gd='git diff --color'
alias gl='git log --graph --pretty=format:"%Cred%h%Creset %C(yellow)%d%Creset %an: %s - %Creset %Cgreen(%cr, %cd)%Creset" --abbrev-commit --date=iso'
alias gs='git status -sb'
alias gf='git fetch --all -p'
alias gp='git push'
alias gpl='git pull'
alias gmm='git merge master'
alias gpum='git pull upstream master'
alias gpom='git pull origin master'
alias gb='git branch'
alias gdb='git branch -D'
