brew install ansible
brew install fontconfig
brew install igbinary
brew install lnav
brew install percona-toolkit
brew install php70-memcached
brew install storm
brew install autoconf
brew install freetype
brew install imagemagick
brew install makedepend
brew install php56
brew install php70-redis
brew install tbb
brew install autojump
brew install gcc48
brew install isl011
brew install mcrypt
brew install php56-amqp
brew install php70-ssh2
brew install the_silver_searcher
brew install automake
brew install gd
brew install jpeg
brew install memcached
brew install php56-apcu
brew install php70-xdebug
brew install tmux
brew install bison
brew install gdbm
brew install lame
brew install mhash
brew install php56-igbinary
brew install pkg-config
brew install tree
brew install bison27
brew install gettext
brew install libarchive
brew install mpfr2
brew install php56-intl
brew install popt
brew install unixodbc
brew install boost
brew install gflags
brew install libelf
brew install mycli
brew install php56-mcrypt
brew install python
brew install unzip
brew install boot-clj
brew install gifsicle
brew install libevent
brew install mysql
brew install php56-memcache
brew install rabbitmq
brew install vim
brew install bsdmake
brew install git
brew install libmemcached
brew install mysql55
brew install php56-memcached
brew install rabbitmq-c
brew install watch
brew install cloog018
brew install git-extras
brew install libmpc08
brew install nginx
brew install php56-redis
brew install re2c
brew install wget
brew install cmake
brew install glog
brew install libpng
brew install node
brew install php56-ssh2
brew install readline
brew install wxmac
brew install curl
brew install gmp
brew install libssh2
brew install oniguruma
brew install php56-xdebug
brew install redis
brew install x264
brew install diff-so-fancy
brew install gmp4
brew install libtiff
brew install openssl
brew install php70
brew install rename
brew install xvid
brew install erlang
brew install grc
brew install libtool
brew install p7zip
brew install php70-amqp
brew install ruby
brew install xz
brew install ffmpeg
brew install htop-osx
brew install libvo-aacenc
brew install parallel
brew install php70-apcu
brew install sbt
brew install zlib
brew install fish
brew install hub
brew install libxml2
brew install pbzip2
brew install php70-intl
brew install sqlite
brew install flex
brew install icu4c
brew install libyaml
brew install pcre
brew install php70-mcrypt
brew install ssh-copy-id
